### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by dnek** [ltentrup/MiniSat#1]
I'd like to use this wrapper in my iOS app and publish it, but since there is no license in this repository, I can't use it for this purpose.

I'm sorry if you intentionally chose no license, but I'm glad if you add a license and specify whether I can use this wrapper.
This is the fastest way.
https://help.github.com/articles/adding-a-license-to-a-repository/

Personally I appreciate MIT or Apache 2.0 licensing.

**Comment by ltentrup** [comment]
Thanks for your request! I've added a license file (MIT).
Let me know if you have any further issues.

**Comment by dnek** [comment]
Thank you for adding the license!
I'll add this wrapper to my app's project later and let you know if there is any issue.

Furthermore, I recommend adding licenses to your other repositories for future visitors if you want them to use your libraries without hesitation.
